### ISSUE TITLE
Auto kill multi login gak work bang

### ISSUE THREAD

**Issue by alfatihart** [wildysheverando-project/autoscript.github.io#1]
![Screenshot_20210406_091201](https://user-images.githubusercontent.com/47027436/113644857-49214c80-96b8-11eb-902e-fbe6a0aa62f8.png)

**Comment by wildysheverando-project** [comment]
Utk auto Kill tidak ada di Script free

Pada tanggal Sel, 6 Apr 2021 08.13, Al-Fatih Art ***@***.***>
menulis:
